### ISSUE TITLE
out-of-tree modules not present on target

### ISSUE THREAD

**Issue by alexus1211** [GloDroid/glodroid_device#11]
Hi,
I am trying to add my own out-of-tree modules to the build, similar to rtl8189es and rtl8189fs, then I just realized that these 2 drivers are not to be found in the target directory.
I am building for the rpi4.
I see the call in kernel.mk to build those, but I am not sure this is enough:
```
include $(LOCAL_PATH)/rtl8189es-mod.mk
include $(LOCAL_PATH)/rtl8189fs-mod.mk
```
any idea?

**Comment by rsglobal** [comment]
Hi @alexus1211 ,

Have you added your modules to PRODUCT_PACKAGES?
Like: https://github.com/GloDroid/glodroid_device/blob/6ad27a5047990119f297fdaef2a10bcfba4b43f9/opi_plus2e/device.mk#L22

**Comment by alexus1211** [comment]
thanks, currently building. I'll report back. 
I was following the approach on https://source.android.com/devices/architecture/kernel/loadable-kernel-modules by using the `BOARD_VENDOR_KERNEL_MODULES `variable as requested.
I am not sure if it works, I'll give it a try.

**Comment by alexus1211** [comment]
it works. Thanks!!!
