### ISSUE TITLE
change in config.txt is not included

### ISSUE THREAD

**Issue by alexus1211** [GloDroid/glodroid_device#13]
I added the following overlay in config.txt for the RPI4 to activate the 1 Wire system:
`dtoverlay=w1-gpio,gpiopin=4`

Furthermore, I added the following lines to the bcm2711_defconfig:
```
CONFIG_W1=y
CONFIG_W1_MASTER_GPIO=m
CONFIG_W1_SLAVE_THERM=m
```

The 1 wire modules have been compiled and moved to _**/vendor/lib/modules/kernel/drivers/w1**_ which is the expected behaviour, but after startup and when issuing the command _lsmod_, I don't see the corresponding modules loaded.
It seems that the overlay in config.txt hasn't been taken into consideration from the build system.

A note aside, the only place where the config.txt is processed is in the script **uboot.mk** as part of the generation of the **bootloader-sd.img** at line 123:
`/usr/bin/mcopy -i $@ $(RPI_CONFIG) ::$(notdir $(RPI_CONFIG))`

what did I miss?

**Comment by rsglobal** [comment]
Hi @alexus1211 ,

Can you check either configuration exists in output .config file or not , path: `out/target/product/rpi4/obj/KERNEL_OBJ/.config` ?

**Comment by alexus1211** [comment]
I can confirm these are set in _.config_ file. I was even been able to load them with _modprobe_ from the `adb shell `as _root_ on the target. Only the **dtoverlay** seems not to be taken into consideration.

```
# CONFIG_GPIO_AGGREGATOR is not set
# CONFIG_GPIO_MOCKUP is not set
CONFIG_W1=y

# CONFIG_W1_MASTER_MATROX is not set
# CONFIG_W1_MASTER_DS2490 is not set
# CONFIG_W1_MASTER_DS2482 is not set
# CONFIG_W1_MASTER_DS1WM is not set
CONFIG_W1_MASTER_GPIO=m
# CONFIG_W1_MASTER_SGI is not set
# end of 1-wire Bus Masters

#
# 1-wire Slaves
#
CONFIG_W1_SLAVE_THERM=m
# CONFIG_W1_SLAVE_SMEM is not set
# CONFIG_W1_SLAVE_DS2405 is not set

```

**Comment by rsglobal** [comment]
Good.

FDT overlaying is done in RPI4 ROM code. Kernel uses same FDT. So things should be same as for Linux.
If you can't see this module in `adb shell lsmod`, try to load it manually.
`adb root && adb shell`
`# insmod /vendor/lib/modules/....`

Or consider embedding modules into the kernel.

**Comment by alexus1211** [comment]
It seems that changes in config.txt are not taken into consideration by the build system on incremental builds.
After a `make clean` and a `make images` commands the changes are considered now. After a cold reboot, an _lsmod_ command shows that the _w1-gpio_ module driver has been loaded successfully.

**Comment by rsglobal** [comment]
Thanks for catching this.

Try to apply this fix: 
```diff
diff --git a/platform/uboot/uboot.mk b/platform/uboot/uboot.mk
index abbbcaa..dafbd7d 100644
--- a/platform/uboot/uboot.mk
+++ b/platform/uboot/uboot.mk
@@ -115,7 +115,7 @@ BOOT_FILES := \
 
 OVERLAY_FILES := $(sort $(shell find -L $(RPI_FIRMWARE_DIR)/boot/overlays))
 
-$(PRODUCT_OUT)/bootloader-sd.img: $(UBOOT_BINARY) $(BOOT_FILES) $(OVERLAY_FILES)
+$(PRODUCT_OUT)/bootloader-sd.img: $(UBOOT_BINARY) $(BOOT_FILES) $(OVERLAY_FILES) $(RPI_CONFIG)
        dd if=/dev/null of=$@ bs=1 count=1 seek=$$(( 128 * 1024 * 1024 - 256 * 512 ))
        /sbin/mkfs.vfat -F 32 -n boot $@
        /usr/bin/mcopy -i $@ $< ::$(notdir $<)
```

I will include in into the next release.

**Comment by alexus1211** [comment]
I can confirm that your patch works :-)
