### ISSUE TITLE
pinephone: android api brightness scaling value

### ISSUE THREAD

**Issue by SrMrBurchick** [GloDroid/glodroid_device#17]
The issue in the next, when you moving a brightness slider from the start up to the middle, the color value of the HwLightState variable changes from 0x0A to 0x20, and then from middle up to the end from 0x20 to 0xFF. (The value it is 4 byte but all bytes except the last has the same values, the last byte is always 0xFF, so we can use only the first byte of it to monitor changes of the brightness) And if we convert it values to the percent we get that in the first case brightness changes from 0% to 12%, but at the phone screen 50% of the brightness slider and then from 12% to 100%.

**Comment by rsglobal** [comment]
Fixed by #16
