### ISSUE TITLE
Extract files for other Allwinner H3 boards (and other Allwinner boards)

### ISSUE THREAD

**Issue by Icenowy** [GloDroid/glodroid_device#2]

**Comment by rsglobal** [comment]
Hello,
I am really pleased to see you here. Thanks a lot for fixing flickering surfaces mesa3d issue and your other huge OSS contribution this project are using.

Adding configuration for H3 boards with 2gb of memory would require just a new lunch list element that make proper DTS selection.

For adding 1gb boards we have to implement and test Google's recommendation from [1] written for v4.2, ad adapt it to the latest AOSP version.

64bit boards require makefile for ATF and testing.

All this is on my list. For now I have OPI-3, OPI-PC, OPI-WIN boards, so hopefully they would be added soon.

[1]: https://source.android.com/devices/tech/perf/low-ram

**Comment by Icenowy** [comment]
@rsglobal I'm working on a port on Pine64 PineTab, which is an A64 tablet.

Currently I am stuck at booting kernel, because the kernel cannot find MMC card.

**Comment by rsglobal** [comment]
@Icenowy ,

Make sure you've specified correct sysfs path to mmc device at https://github.com/glodroid/glodroid_device/blob/47b8977abe5b15da73aaf13ce86e29760840509f/uboot/boot.txt#L31

PS:
I believe it should be `soc/1c11000.mmc` for pine64 and other A64-based devices

**Comment by Icenowy** [comment]
@rsglobal It's not the bootdevice path is wrong. It's MMC controlled being not probed.

BTW if I do not use eMMC, it's still 1c0f000.

**Comment by Icenowy** [comment]
https://pastebin.aosc.io/paste/v3V1VQtvn5l929A53M00ug Here's the log of the hacked boot.

I don't know why but sunxi-mmc doesn't probe.

**Comment by Icenowy** [comment]
I added kernel parameter hack `of_devlink=0`, and it boots now.

Now I'm facing a critical exception in zygote:

`java.lang.RuntimeException: Unable to connect to zygote for abi: armeabi-v7a`

**Comment by Icenowy** [comment]
@rsglobal Thanks. I saw you're WiP on this.

I will try to synchronize to port Pine devices support on top of your effort.

BTW I'm asking TL Lim whether he can ship a set of Pine devices to you ;-)

**Comment by rsglobal** [comment]
@Icenowy,

> https://pastebin.aosc.io/paste/v3V1VQtvn5l929A53M00ug Here's the log of the hacked boot.
> I don't know why but sunxi-mmc doesn't probe.

It seems that you are using preview-4. Since v0.1.0 boot flow changed, so switching to newer version may help.

> @rsglobal Thanks. I saw you're WiP on this.

I've added initial support for 64-bit SOCs in the next branch.
If you can align your work with next branch and make it visible, then I could support you where it possible.

> I will try to synchronize to port Pine devices support on top of your effort.
> BTW I'm asking TL Lim whether he can ship a set of Pine devices to you ;-)

It would be awesome.

Also maybe you know good source of base defconfig for 64bit sunxi platform I can reuse here?
Kernel offers only common defconfig therefore I expect to spend a lot of time tuning it.

**Comment by rsglobal** [comment]
I believe these guys should have some stable and maintainable:
https://github.com/armbian/build/blob/master/config/kernel/linux-sunxi64-current.config

**Comment by Icenowy** [comment]
https://github.com/Icenowy/glodroid_device/tree/pinetab I added PineTab support there.

However,it doesn't boot currently, with such log: https://pastebin.aosc.io/paste/MWG-KvibQ4noqnIEh33KvQ

**Comment by Icenowy** [comment]
On PineTab /dev/dri/card0 is Lima and /dev/dri/card1 is Allwinner Display Engine.

Any idea to handle this?

**Comment by Icenowy** [comment]
The issue in https://github.com/glodroid/glodroid_device/issues/2#issuecomment-595645317 is because recovery is not correctly launched to format /data .

**Comment by rsglobal** [comment]
```diff
--- a/platform/uboot/boot.txt
+++ b/platform/uboot/boot.txt
@@ -11,5 +11,5 @@ setenv bootargs "
 
 setenv bootcmd_bcb '
- bcb load $mmc_index misc ;
+ bcb load $mmc_bootdev misc ;
  bcb test command = bootonce-bootloader && bcb set command boot-fastboot && bcb store && setenv androidrecovery true ;
  bcb test command = boot-recovery && setenv androidrecovery true ;
```

PS:
Ah, I saw your similar fix just now.

**Comment by rsglobal** [comment]
> On PineTab /dev/dri/card0 is Lima and /dev/dri/card1 is Allwinner Display Engine.
> 
> Any idea to handle this?

Is `pinetab: hack for dri/card1` commit solved the issue?

**Comment by Icenowy** [comment]
Yes, this hack solves it.
