### ISSUE TITLE
v0.7.0 tag stuck at commit 52dcc9c when repo sync

### ISSUE THREAD

**Issue by Road-Drum** [GloDroid/glodroid_device#28]
I'm using the `next` branch for glodroid manifest and noticed `glodroid_device` commit never went past https://github.com/GloDroid/glodroid_device/commit/52dcc9c452d070ba61d10f92b1ad1d1099fcea05 

I can confirm the manifest is using [v0.7.0](https://github.com/GloDroid/glodroid_device/tree/v0.7.0) tag for `glodroid device`. snippet of my `glodroid.xml`

```
  <project path="device/glodroid"        remote="glodroid" name="glodroid_device.git"        revision="refs/tags/v0.7.0" />
```

after repo sync, checking the git log shows

```
$ git log
commit 52dcc9c452d070ba61d10f92b1ad1d1099fcea05 (HEAD, tag: v0.7.0, m/next-staging, m/next)
Author: Roman Stratiienko <redacted email>
Date:   Thu Nov 11 18:27:08 2021 +0200

    rpi4: Fix USB flash devices automount
    
    Closes: https://github.com/GloDroid/glodroid_manifest/issues/146
    Signed-off-by: Roman Stratiienko <redacted email>
```

While the most recent commit for that tag is https://github.com/GloDroid/glodroid_device/commit/a3917c2a49360951603bcf7ca01b99e1bb5aa04e

I've manually removed the entire `glodroid_device` directory and run repo sync to fetch them again but the result is the same so I decided to manually git clone and see if it produces the same behavior

```
$ git clone https://github.com/GloDroid/glodroid_device.git -b v0.7.0
Cloning into 'glodroid_device'...
remote: Enumerating objects: 2969, done.
remote: Counting objects: 100% (661/661), done.
remote: Compressing objects: 100% (380/380), done.
remote: Total 2969 (delta 378), reused 486 (delta 245), pack-reused 2308
Receiving objects: 100% (2969/2969), 1.28 MiB | 8.76 MiB/s, done.
Resolving deltas: 100% (1843/1843), done.
Note: switching to 'a3917c2a49360951603bcf7ca01b99e1bb5aa04e'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false
```

I could set revision to https://github.com/GloDroid/glodroid_device/commit/a3917c2a49360951603bcf7ca01b99e1bb5aa04e but probably worth to notify you that this commit is in detached state

**Comment by rsglobal** [comment]
Hi, v0.7.0 isn't yet officially released and continuously updating with fixes. next branch is currently aligned with v0.7.0
What you are experiencing is a result of my force-push into the tags.
Removing all android tree and fetching again is the most reliable way to fix this.
Also you may update glodroid-specific repos using `git fetch glodroid --prune --tags -f` and then checkout v0.7.0
