### ISSUE TITLE
Flashing instructions for RPI4

### ISSUE THREAD

**Issue by amsurana** [GloDroid/glodroid_device#30]
Hi, 

I am trying to find instructions required for flashing RPI4. However, looks like I am constantly getting bad flashing on my SDcard and unable to move forward. Looking for some support if possible.

I cloned glodroid code and built it successfully. 

I ran both:
- m -j16 systemimage vendorimage ramdisk
- make images

I thought I will flash all the partitions using `dd` command and get it done. 
However, after flashing, the device is not booting at all. All I see is a blank screen. 

Next, I tried flashing images from `images.tar.gz`. When I untar the files, I first flashed `deploy-sd.img` through `rpi-imager` tool. But tht produced bad GPT partition. I figured this out when I run `gparted` program in Ubuntu machine. It showed that the partition is corrupted. RPI4 too did not recognize the recovery partitions and failed to boot successfully.

Any help will be greatly appreciated.

**Comment by rsglobal** [comment]
Hi @amsurana , 

Our manifest repo is more appropriate place for such kind of issues.

> RPI4 too did not recognize the recovery partitions and failed to boot successfully.

It should enter fastboot mode and further flashing should be done via `fastboot`, by running flash-sd.sh script. Please follow manual from manifest repo: https://github.com/GloDroid/glodroid_manifest#step-3
