### ISSUE TITLE
Improving collaboration between Android distributions that use mainline based kernels

### ISSUE THREAD

**Issue by GNUtoo** [GloDroid/glodroid_device#32]
Hi,

I've looked at this repository and it seems to have generic code that could also be useful for other Android distributions.

* It has an USB Gadget HAL and I've not looked into details but the code seems to be generic.
* It has .mk files for building various projects (Linux, u-boot, etc).
* It has a vibrator HAL

Other distributions also use kernels based on upstream Linux:

  * Anbox (based on AOSP, goal: run Android applications in GNU/Linux)
  * Android x86 (Based on AOSP, goal: run Android on x86 computers)
  * AOSP Mainline (Based on AOSP)
  * GloDroid (Based on AOSP, goal: support certain devices?)
  * Replicant 11 (based on AOSP, goals: 100% free software, support devices with isolated modem and removable batteries)
  * Waydroid (Based on LineageOS, goal: run Android applications in GNU/Linux)

So I was wondering if there was a way to improve collaboration. For instance AOSP Mainline and Replicant also wrote a vibrator HAL.

I've also contacted AOSP Mainline [1] to see if we could find ways to share the maintenance.

In the case of GLODroid, would it accept patches to split generic HALs so that they could be reused as-is by other Android distributions?

It would also be a good idea to have a way to easily find the generic HALs that work with upstream kernels to avoid reinventing the wheel. I wonder if the way to go is to work on upstreaming these, or if we should somehow maintain them in a separate project.

References:
---------------
[1]https://github.com/aospm/android_local_manifests/issues/3

Denis.

**Comment by rsglobal** [comment]
Hi,

Did you have a chance to read this page https://aosp-developers-community.github.io/ ?

**Comment by GNUtoo** [comment]
On Sat, 26 Nov 2022 10:08:00 -0800
rsglobal ***@***.***> wrote:

> Hi,
Hi,

> Did you have a chance to read this page
> https://aosp-developers-community.github.io/ ?
I didn't know it existed.

This answer my questions as there are links to projects that are meant
to be shared between several AOSP distributions.

Thanks a lot for the information.

Denis.
